<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Netresearch Open Source Inventory</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/paper/bootstrap.min.css">
    <base target="_blank">
    <link href='//cdn.jsdelivr.net/devicons/1.8.0/css/devicons.min.css' rel='stylesheet'>
    <style type="text/css">
        a.json-toggle.collapsed:before {
            font-size: 10px;
            top: -1px;
            left:-11px;
        }
        body {
            padding-top:65px;
        }
        .container {
            max-width:860px;
        }
        .jumbotron {
            margin: 0;
            border-radius: 6px;
        }
        .github svg {
            width:20px;
            height:20px;
            margin: -5px 0;
            fill: currentColor;
        }
        .panel-heading > h4 {
            position: relative;
            padding:4px 0;
            padding-left:30px;
        }
        .panel-heading > h4 > img {
            max-width:24px;
            max-height:24px;
            position: absolute;
            left:-3px;
            top:0;
        }
        .panel-heading > h4 > span {
            color: #2F99A4;
            font-size:22px;
            font-weight: normal;
            position: absolute;
            left:-3px;
            top:0;
            margin-right:6px;
        }
        .panel-heading > h4 > span.devicons {
            font-size: 26px;
        }
        .panel-heading > h4 > .elm {
            display:block;
            width:24px;
            height: 24px;
            font-size:12px;
            line-height: 20px;
            white-space: nowrap;
            text-align: center;
            border: 2px solid #2F99A4;
            font-weight: 700;
        }
        .panel-footer > a {
            color: #666;
            margin-right:10px;
            position: relative;
            float:left;
            top:-1px;
            opacity: 0.9;
            transition: all 0.2s;
        }
        .panel-footer > a:hover {
            text-decoration: none;
            color: #2F99A4;
            opacity: 1;
        }
        .panel-footer .dropdown {
            display: inline-block;
            position: relative;
            float:left;
        }
        .panel-footer .dropdown > span {
            display: inline-block;
            height:20px;
            padding:0 6px 0;
            position: relative;
            top:2px;
        }
        .panel-footer .dropdown > span:hover,
        .panel-footer .dropdown.open > span {
            background: #d8d8d8;
            border-radius: 3px;
        }
        .badge {
            vertical-align: baseline;
            display: inline-block;
            border-radius: 4px;
            background: #666;
            height:20px;
            line-height: 18px;
            position: relative;
            top:1px;
            padding: 0 6px 0 26px;
            color:#fff;
        }
        .badge:before {
            content: "\e672";
            font-family: devicons;
            background: #f58006;
            color:#fff;
            position: absolute;
            left:0;
            top:0;
            bottom:0;
            height: 100%;
            line-height: 20px;
            width:20px;
            text-align: center;
            border-radius: 4px 0 0 4px;
            font-size:16px;
        }
        .badge.github:before {
            content:"\e609";
            background: #333;
        }
        .badge.docker:before {
            content: " ";
            display: block;
            background: url("img/docker.svg") #13a3d4 no-repeat center;
            background-size: 18px;
        }
        .badge.npm {
            padding-left: 32px;
        }
        .badge.npm:before {
            content:"\e61e";
            background: #C12127;
            font-size:18px;
            width:26px;
        }
        .badge.packagist:before {
            content: "P";
            line-height: 18px;
            background: #f28d1a
        }

    </style>
</head>
<body>

<?php
$library = require __DIR__ . '/library.php';
function getId($title) {
    static $ids = [];
    $id = $origId = str_replace(' ', '-', strtolower($title));
    $i = 1;
    while (array_key_exists($id, $ids)) {
        $id = $origId . '-' . $i;
        $i++;
    }
    $ids[$id] = $title;
    return $id;
}
foreach ($library as $group => $items) {
    $library[$group]['id'] = getId($group);
    foreach ($items as $title => $item) {
        $library[$group][$title]['id'] = getId($title);
    }
}
?>

<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><img src="img/netresearch.png" height="24" alt="Netresearch"></a>
            <a class="navbar-brand" href="#">Open Source Inventory</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
            <ul class="nav navbar-nav navbar-right">
                <?php foreach ($library as $group => $items): ?>
                    <li class="dropdown">
                        <a data-target="#" href="#<?php echo $items['id'] ?>" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <?php echo $group ?>
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <?php foreach ($items as $title => $item): ?>
                                <?php if ($title === 'id') continue; ?>
                                <li><a target="_self" href="#<?php echo $item['id'] ?>"><?php echo $title ?></a></li>
                            <?php endforeach; ?>
                        </ul>
                    </li>
                <?php endforeach; ?>
                <li>
                    <a class="github" href="https://github.com/netresearch" target="_blank" title="Netresearch on GitHub">
                        <svg aria-hidden="true" viewBox="0 0 16 16"><path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z"></path></svg>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <div class="jumbotron">
        <h2><span style="color:#2F99A4">Netresearch</span><br>Open Source Inventory</h2>
        <p>The greatest and latest of Netresearch's Open Source Initiatives</p>
    </div>
    <?php foreach ($library as $group => $items): ?>
        <h3 id="<?php echo $items['id'] ?>"><?php echo $group ?></h3>
        <hr>
        <?php foreach ($items as $title => $item): ?>
            <?php if ($title === 'id') continue; ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 id="<?php echo $item['id'] ?>" class="panel-title">
                        <?php if (isset($item['glyphicon'])): ?>
                        <span class="glyphicon glyphicon-<?php echo $item['glyphicon'] ?>"></span>
                        <?php elseif (isset($item['devicon'])): ?>
                        <span class="devicons devicons-<?php echo $item['devicon'] ?>"></span>
                        <?php elseif (isset($item['img'])): ?>
                        <img src="img/library/<?php echo $item['img'] ?>" alt="">
                        <?php elseif (isset($item['elm'])): ?>
                        <span class="elm"><?php echo $item['elm'] ?></span>
                        <?php endif; ?>
                        <?php echo $title; ?>
                    </h4>
                </div>
                <div class="panel-body"><?php echo $item['desc']; ?></div>
                <div class="panel-footer clearfix">
                    <?php foreach ($item['badges'] as $badge => $types): ?>
                        <?php $badgeTitle = substr($badge, 0, 4) === 't3x-' ? substr($badge, 4) : $badge; ?>
                        <?php foreach ((array) $types as $type): ?>
                            <a href="<?php
                                if ($type == 'github') {
                                    echo 'https://github.com/netresearch/' . $badge;
                                } elseif ($type === 'ter') {
                                    echo 'https://typo3.org/extensions/repository/view/' . $badge;
                                } elseif ($type === 'travis') {
                                    echo 'https://travis-ci.org/netresearch/' . $badge;
                                } elseif ($type === 'docker') {
                                    echo 'https://hub.docker.com/r/netresearch/' . $badge;
                                } elseif ($type === 'npm') {
                                    echo 'https://www.npmjs.com/package/' . $badge;
                                } elseif ($type === 'packagist') {
                                    echo 'https://packagist.org/packages/netresearch/' . $badge;
                                }
                            ?>"
                               title="<?php
                                echo $badgeTitle . ' on ';
                                echo $type === 'github' ? 'GitHub' : ($type === 'ter' ? 'TER' : ($type === 'docker' ? 'Docker Hub' : $type))
                               ?>">
                                <?php if ($type === 'travis'): ?>
                                    <img src="https://api.travis-ci.org/netresearch/<?php echo $badge ?>.png">
                                <?php else: ?>
                                    <span class="badge <?php echo $type; ?>"><?php echo $badgeTitle ?></span>
                                <?php endif; ?>
                            </a>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                    <?php if (isset($item['more'])): ?>
                        <div class="dropdown">
                            <span data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="glyphicon glyphicon-option-horizontal"></span>
                            </span>
                            <ul class="dropdown-menu">
                                <?php foreach ($item['more'] as $url => $linkTitle): ?>
                                    <li><a href="<?php echo $url ?>"><?php echo $linkTitle ?></a></li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        <?php endforeach; ?>
    <?php endforeach; ?>
</div>

<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-411352-19', 'auto');
    ga('send', 'pageview');
</script>
</body>
</html>
