/**
 * Review metadata for the hub itself.
 *
 * `lastVerified` records when a person last checked this site's non-derived
 * copy — the business and governance statements that no script can validate.
 * It is deliberately not a version and not a build timestamp. verify-site.mjs
 * fails the build once it is older than MAX_AGE_DAYS.
 */
export const site = {
  lastVerified: '2026-08-10',
  owner: 'Netresearch DTT GmbH — Open Source Team',
  /** Campaign name used in every UTM-tagged contact link on this site. */
  utmCampaign: 'portfolio',
  contact: 'https://www.netresearch.de/kontakt/',
  imprint: 'https://www.netresearch.de/impressum/',
  privacy: 'https://www.netresearch.de/datenschutz/',
  company: 'https://www.netresearch.de/',
  github: 'https://github.com/netresearch',
} as const;

/** Copy older than this fails the build rather than quietly ageing on the page. */
export const MAX_VERIFIED_AGE_DAYS = 180;

/**
 * Social preview cards, one per language, generated by scripts/build-og-image.mjs
 * from the same headline the page renders.
 */
export const ogImage: Record<'en' | 'de', string> = {
  en: '/img/og-portfolio-en.png',
  de: '/img/og-portfolio-de.png',
};
